name: Preview Publish
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  publish:
    runs-on: marcduiker-medium
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Persist npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist Eleventy .cache
        uses: actions/cache@v4
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache
      - run: npm install --os=linux --cpu=x64 sharp
      - run: npm install
      - run: npm run build
        env:
          URL: "https://marcduiker.dev"
          ELEVENTY_PATH_PREFIX: "/marcduiker-dev"
      - name: Publish to Codeberg Pages
        if: ${{ forge.ref == 'refs/heads/main' || forge.event_name == 'workflow_dispatch' || forge.event_name == 'push' }}
        uses: actions/git-pages@v2
        with:
          site: https://${{ forge.event.repository.owner.username }}.codeberg.page/${{ forge.event.repository.name }}/
          token: ${{ forge.token }}
          source: ./dist